import enum
import typing as T
from dataclasses import dataclass

from pqcli.i18n import N_


class StatType(enum.Enum):
    strength = N_("STR")
    condition = N_("CON")
    dexterity = N_("DEX")
    intelligence = N_("INT")
    wisdom = N_("WIS")
    charisma = N_("CHA")
    hp_max = N_("HP Max")
    mp_max = N_("MP Max")


class EquipmentType(enum.Enum):
    weapon = N_("Weapon")
    shield = N_("Shield")
    helm = N_("Helm")
    hauberk = N_("Hauberk")
    brassairts = N_("Brassairts")
    vambraces = N_("Vambraces")
    gauntlets = N_("Gauntlets")
    gambeson = N_("Gambeson")
    cuisses = N_("Cuisses")
    greaves = N_("Greaves")
    sollerets = N_("Sollerets")


PRIME_STATS = [
    StatType.strength,
    StatType.condition,
    StatType.dexterity,
    StatType.intelligence,
    StatType.wisdom,
    StatType.charisma,
]

ALL_STATS = PRIME_STATS + [StatType.hp_max, StatType.mp_max]


SPELLS = [
    N_("Slime Finger"),
    N_("Rabbit Punch"),
    N_("Hastiness"),
    N_("Good Move"),
    N_("Sadness"),
    N_("Seasick"),
    N_("Shoelaces"),
    N_("Inoculate"),
    N_("Cone of Annoyance"),
    N_("Magnetic Orb"),
    N_("Invisible Hands"),
    N_("Revolting Cloud"),
    N_("Aqueous Humor"),
    N_("Spectral Miasma"),
    N_("Clever Fellow"),
    N_("Lockjaw"),
    N_("History Lesson"),
    N_("Hydrophobia"),
    N_("Big Sister"),
    N_("Cone of Paste"),
    N_("Mulligan"),
    N_("Nestor's Bright Idea"),
    N_("Holy Batpole"),
    N_("Tumor (Benign)"),
    N_("Braingate"),
    N_("Summon a Bitch"),
    N_("Nonplus"),
    N_("Animate Nightstand"),
    N_("Eye of the Troglodyte"),
    N_("Curse Name"),
    N_("Dropsy"),
    N_("Vitreous Humor"),
    N_("Roger's Grand Illusion"),
    N_("Covet"),
    N_("Black Idaho"),
    N_("Astral Miasma"),
    N_("Spectral Oyster"),
    N_("Acrid Hands"),
    N_("Angioplasty"),
    N_("Grognor's Big Day Off"),
    N_("Tumor (Malignant)"),
    N_("Animate Tunic"),
    N_("Ursine Armor"),
    N_("Holy Roller"),
    N_("Tonsillectomy"),
    N_("Curse Family"),
    N_("Infinite Confusion"),
]


@dataclass
class Modifier:
    name: str
    quality: int


OFFENSE_ATTRIB = [
    Modifier(N_("Polished"), 1),
    Modifier(N_("Serrated"), 1),
    Modifier(N_("Heavy"), 1),
    Modifier(N_("Pronged"), 2),
    Modifier(N_("Steely"), 2),
    Modifier(N_("Vicious"), 3),
    Modifier(N_("Venomed"), 4),
    Modifier(N_("Stabbity"), 4),
    Modifier(N_("Dancing"), 5),
    Modifier(N_("Invisible"), 6),
    Modifier(N_("Vorpal"), 7),
]

DEFENSE_ATTRIB = [
    Modifier(N_("Studded"), 1),
    Modifier(N_("Banded"), 2),
    Modifier(N_("Gilded"), 2),
    Modifier(N_("Festooned"), 3),
    Modifier(N_("Holy"), 4),
    Modifier(N_("Cambric"), 1),
    Modifier(N_("Fine"), 4),
    Modifier(N_("Impressive"), 5),
    Modifier(N_("Custom"), 3),
]

OFFENSE_BAD = [
    Modifier(N_("Dull"), -2),
    Modifier(N_("Tarnished"), -1),
    Modifier(N_("Rusty"), -3),
    Modifier(N_("Padded"), -5),
    Modifier(N_("Bent"), -4),
    Modifier(N_("Mini"), -4),
    Modifier(N_("Rubber"), -6),
    Modifier(N_("Nerf"), -7),
    Modifier(N_("Unbalanced"), -2),
]

DEFENSE_BAD = [
    Modifier(N_("Holey"), -1),
    Modifier(N_("Patched"), -1),
    Modifier(N_("Threadbare"), -2),
    Modifier(N_("Faded"), -1),
    Modifier(N_("Rusty"), -3),
    Modifier(N_("Motheaten"), -3),
    Modifier(N_("Mildewed"), -2),
    Modifier(N_("Torn"), -3),
    Modifier(N_("Dented"), -3),
    Modifier(N_("Cursed"), -5),
    Modifier(N_("Plastic"), -4),
    Modifier(N_("Cracked"), -4),
    Modifier(N_("Warped"), -3),
    Modifier(N_("Corroded"), -3),
]


@dataclass
class EquipmentPreset:
    name: str
    quality: int


SHIELDS = [
    EquipmentPreset(N_("Parasol"), 0),
    EquipmentPreset(N_("Pie Plate"), 1),
    EquipmentPreset(N_("Garbage Can Lid"), 2),
    EquipmentPreset(N_("Buckler"), 3),
    EquipmentPreset(N_("Plexiglass"), 4),
    EquipmentPreset(N_("Fender"), 4),
    EquipmentPreset(N_("Round Shield"), 5),
    EquipmentPreset(N_("Carapace"), 5),
    EquipmentPreset(N_("Scutum"), 6),
    EquipmentPreset(N_("Propugner"), 6),
    EquipmentPreset(N_("Kite Shield"), 7),
    EquipmentPreset(N_("Pavise"), 8),
    EquipmentPreset(N_("Tower Shield"), 9),
    EquipmentPreset(N_("Baroque Shield"), 11),
    EquipmentPreset(N_("Aegis"), 12),
    EquipmentPreset(N_("Magnetic Field"), 18),
]

ARMORS = [
    EquipmentPreset(N_("Lace"), 1),
    EquipmentPreset(N_("Macrame"), 2),
    EquipmentPreset(N_("Burlap"), 3),
    EquipmentPreset(N_("Canvas"), 4),
    EquipmentPreset(N_("Flannel"), 5),
    EquipmentPreset(N_("Chamois"), 6),
    EquipmentPreset(N_("Pleathers"), 7),
    EquipmentPreset(N_("Leathers"), 8),
    EquipmentPreset(N_("Bearskin"), 9),
    EquipmentPreset(N_("Ringmail"), 10),
    EquipmentPreset(N_("Scale Mail"), 12),
    EquipmentPreset(N_("Chainmail"), 14),
    EquipmentPreset(N_("Splint Mail"), 15),
    EquipmentPreset(N_("Platemail"), 16),
    EquipmentPreset(N_("ABS"), 17),
    EquipmentPreset(N_("Kevlar"), 18),
    EquipmentPreset(N_("Titanium"), 19),
    EquipmentPreset(N_("Mithril Mail"), 20),
    EquipmentPreset(N_("Diamond Mail"), 25),
    EquipmentPreset(N_("Plasma"), 30),
]

WEAPONS = [
    EquipmentPreset(N_("Stick"), 0),
    EquipmentPreset(N_("Broken Bottle"), 1),
    EquipmentPreset(N_("Shiv"), 1),
    EquipmentPreset(N_("Sprig"), 1),
    EquipmentPreset(N_("Oxgoad"), 1),
    EquipmentPreset(N_("Eelspear"), 2),
    EquipmentPreset(N_("Bowie Knife"), 2),
    EquipmentPreset(N_("Claw Hammer"), 2),
    EquipmentPreset(N_("Handpeen"), 2),
    EquipmentPreset(N_("Andiron"), 3),
    EquipmentPreset(N_("Hatchet"), 3),
    EquipmentPreset(N_("Tomahawk"), 3),
    EquipmentPreset(N_("Hackbarm"), 3),
    EquipmentPreset(N_("Crowbar"), 4),
    EquipmentPreset(N_("Mace"), 4),
    EquipmentPreset(N_("Battleadze"), 4),
    EquipmentPreset(N_("Leafmace"), 5),
    EquipmentPreset(N_("Shortsword"), 5),
    EquipmentPreset(N_("Longiron"), 5),
    EquipmentPreset(N_("Poachard"), 5),
    EquipmentPreset(N_("Baselard"), 5),
    EquipmentPreset(N_("Whinyard"), 6),
    EquipmentPreset(N_("Blunderbuss"), 6),
    EquipmentPreset(N_("Longsword"), 6),
    EquipmentPreset(N_("Crankbow"), 6),
    EquipmentPreset(N_("Blibo"), 7),
    EquipmentPreset(N_("Broadsword"), 7),
    EquipmentPreset(N_("Kreen"), 7),
    EquipmentPreset(N_("Warhammer"), 7),
    EquipmentPreset(N_("Morning Star"), 8),
    EquipmentPreset(N_("Pole-adze"), 8),
    EquipmentPreset(N_("Spontoon"), 8),
    EquipmentPreset(N_("Bastard Sword"), 9),
    EquipmentPreset(N_("Peen-arm"), 9),
    EquipmentPreset(N_("Culverin"), 10),
    EquipmentPreset(N_("Lance"), 10),
    EquipmentPreset(N_("Halberd"), 11),
    EquipmentPreset(N_("Poleax"), 12),
    EquipmentPreset(N_("Bandyclef"), 15),
]

SPECIALS = [
    N_("Diadem"),
    N_("Festoon"),
    N_("Gemstone"),
    N_("Phial"),
    N_("Tiara"),
    N_("Scabbard"),
    N_("Arrow"),
    N_("Lens"),
    N_("Lamp"),
    N_("Hymnal"),
    N_("Fleece"),
    N_("Laurel"),
    N_("Brooch"),
    N_("Gimlet"),
    N_("Cobble"),
    N_("Albatross"),
    N_("Brazier"),
    N_("Bandolier"),
    N_("Tome"),
    N_("Garnet"),
    N_("Amethyst"),
    N_("Candelabra"),
    N_("Corset"),
    N_("Sphere"),
    N_("Sceptre"),
    N_("Ankh"),
    N_("Talisman"),
    N_("Orb"),
    N_("Gammel"),
    N_("Ornament"),
    N_("Brocade"),
    N_("Galoon"),
    N_("Bijou"),
    N_("Spangle"),
    N_("Gimcrack"),
    N_("Hood"),
    N_("Vulpeculum"),
]

ITEM_ATTRIB = [
    N_("Golden"),
    N_("Gilded"),
    N_("Spectral"),
    N_("Astral"),
    N_("Garlanded"),
    N_("Precious"),
    N_("Crafted"),
    N_("Dual"),
    N_("Filigreed"),
    N_("Cruciate"),
    N_("Arcane"),
    N_("Blessed"),
    N_("Reverential"),
    N_("Lucky"),
    N_("Enchanted"),
    N_("Gleaming"),
    N_("Grandiose"),
    N_("Sacred"),
    N_("Legendary"),
    N_("Mythic"),
    N_("Crystalline"),
    N_("Austere"),
    N_("Ostentatious"),
    N_("One True"),
    N_("Proverbial"),
    N_("Fearsome"),
    N_("Deadly"),
    N_("Benevolent"),
    N_("Unearthly"),
    N_("Magnificent"),
    N_("Iron"),
    N_("Ormolu"),
    N_("Puissant"),
]

ITEM_OFS = [
    N_("Foreboding"),
    N_("Foreshadowing"),
    N_("Nervousness"),
    N_("Happiness"),
    N_("Torpor"),
    N_("Danger"),
    N_("Craft"),
    N_("Silence"),
    N_("Invisibility"),
    N_("Rapidity"),
    N_("Pleasure"),
    N_("Practicality"),
    N_("Hurting"),
    N_("Joy"),
    N_("Petulance"),
    N_("Intrusion"),
    N_("Chaos"),
    N_("Suffering"),
    N_("Extroversion"),
    N_("Frenzy"),
    N_("Sisu"),
    N_("Solitude"),
    N_("Punctuality"),
    N_("Efficiency"),
    N_("Comfort"),
    N_("Patience"),
    N_("Internment"),
    N_("Incarceration"),
    N_("Misapprehension"),
    N_("Loyalty"),
    N_("Envy"),
    N_("Acrimony"),
    N_("Worry"),
    N_("Fear"),
    N_("Awe"),
    N_("Guile"),
    N_("Prurience"),
    N_("Fortune"),
    N_("Perspicacity"),
    N_("Domination"),
    N_("Submission"),
    N_("Fealty"),
    N_("Hunger"),
    N_("Despair"),
    N_("Cruelty"),
    N_("Grob"),
    N_("Dignard"),
    N_("Ra"),
    N_("the Bone"),
    N_("Diamonique"),
    N_("Electrum"),
    N_("Hydragyrum"),
]

BORING_ITEMS = [
    N_("nail"),
    N_("lunchpail"),
    N_("sock"),
    N_("I.O.U."),
    N_("cookie"),
    N_("pint"),
    N_("toothpick"),
    N_("writ"),
    N_("newspaper"),
    N_("letter"),
    N_("plank"),
    N_("hat"),
    N_("egg"),
    N_("coin"),
    N_("needle"),
    N_("bucket"),
    N_("ladder"),
    N_("chicken"),
    N_("twig"),
    N_("dirtclod"),
    N_("counterpane"),
    N_("vest"),
    N_("teratoma"),
    N_("bunny"),
    N_("rock"),
    N_("pole"),
    N_("carrot"),
    N_("canoe"),
    N_("inkwell"),
    N_("hoe"),
    N_("bandage"),
    N_("trowel"),
    N_("towel"),
    N_("planter box"),
    N_("anvil"),
    N_("axle"),
    N_("tuppence"),
    N_("casket"),
    N_("nosegay"),
    N_("trinket"),
    N_("credenza"),
    N_("writ"),
]


@dataclass
class Monster:
    name: str
    level: int
    item: T.Optional[str]


MONSTERS = [
    Monster(N_("Anhkheg"), 6, N_("chitin")),
    Monster(N_("Ant"), 0, N_("antenna")),
    Monster(N_("Ape"), 4, N_("ass")),
    Monster(N_("Baluchitherium"), 14, N_("ear")),
    Monster(N_("Beholder"), 10, N_("eyestalk")),
    Monster(N_("Black Pudding"), 10, N_("saliva")),
    Monster(N_("Blink Dog"), 4, N_("eyelid")),
    Monster(N_("Cub Scout"), 1, N_("neckerchief")),
    Monster(N_("Girl Scout"), 2, N_("cookie")),
    Monster(N_("Boy Scout"), 3, N_("merit badge")),
    Monster(N_("Eagle Scout"), 4, N_("merit badge")),
    Monster(N_("Bugbear"), 3, N_("skin")),
    Monster(N_("Bugboar"), 3, N_("tusk")),
    Monster(N_("Boogie"), 3, N_("slime")),
    Monster(N_("Camel"), 2, N_("hump")),
    Monster(N_("Carrion Crawler"), 3, N_("egg")),
    Monster(N_("Catoblepas"), 6, N_("neck")),
    Monster(N_("Centaur"), 4, N_("rib")),
    Monster(N_("Centipede"), 0, N_("leg")),
    Monster(N_("Cockatrice"), 5, N_("wattle")),
    Monster(N_("Couatl"), 9, N_("wing")),
    Monster(N_("Crayfish"), 0, N_("antenna")),
    Monster(N_("Demogorgon"), 53, N_("tentacle")),
    Monster(N_("Jubilex"), 17, N_("gel")),
    Monster(N_("Manes"), 1, N_("tooth")),
    Monster(N_("Orcus"), 27, N_("wand")),
    Monster(N_("Succubus"), 6, N_("bra")),
    Monster(N_("Vrock"), 8, N_("neck")),
    Monster(N_("Hezrou"), 9, N_("leg")),
    Monster(N_("Glabrezu"), 10, N_("collar")),
    Monster(N_("Nalfeshnee"), 11, N_("tusk")),
    Monster(N_("Marilith"), 7, N_("arm")),
    Monster(N_("Balor"), 8, N_("whip")),
    Monster(N_("Yeenoghu"), 25, N_("flail")),
    Monster(N_("Asmodeus"), 52, N_("leathers")),
    Monster(N_("Baalzebul"), 43, N_("pants")),
    Monster(N_("Barbed Devil"), 8, N_("flame")),
    Monster(N_("Bone Devil"), 9, N_("hook")),
    Monster(N_("Dispater"), 30, N_("matches")),
    Monster(N_("Erinyes"), 6, N_("thong")),
    Monster(N_("Geryon"), 30, N_("cornucopia")),
    Monster(N_("Malebranche"), 5, N_("fork")),
    Monster(N_("Ice Devil"), 11, N_("snow")),
    Monster(N_("Lemure"), 3, N_("blob")),
    Monster(N_("Pit Fiend"), 13, N_("seed")),
    Monster(N_("Ankylosaurus"), 9, N_("tail")),
    Monster(N_("Brontosaurus"), 30, N_("brain")),
    Monster(N_("Diplodocus"), 24, N_("fin")),
    Monster(N_("Elasmosaurus"), 15, N_("neck")),
    Monster(N_("Gorgosaurus"), 13, N_("arm")),
    Monster(N_("Iguanadon"), 6, N_("thumb")),
    Monster(N_("Megalosaurus"), 12, N_("jaw")),
    Monster(N_("Monoclonius"), 8, N_("horn")),
    Monster(N_("Pentasaurus"), 12, N_("head")),
    Monster(N_("Stegosaurus"), 18, N_("plate")),
    Monster(N_("Triceratops"), 16, N_("horn")),
    Monster(N_("Tyrannosaurus Rex"), 18, N_("forearm")),
    Monster(N_("Djinn"), 7, N_("lamp")),
    Monster(N_("Doppelganger"), 4, N_("face")),
    Monster(N_("Black Dragon"), 7, None),
    Monster(N_("Plaid Dragon"), 7, N_("sporrin")),
    Monster(N_("Blue Dragon"), 9, None),
    Monster(N_("Beige Dragon"), 9, None),
    Monster(N_("Brass Dragon"), 7, N_("pole")),
    Monster(N_("Tin Dragon"), 8, None),
    Monster(N_("Bronze Dragon"), 9, N_("medal")),
    Monster(N_("Chromatic Dragon"), 16, N_("scale")),
    Monster(N_("Copper Dragon"), 8, N_("loafer")),
    Monster(N_("Gold Dragon"), 8, N_("filling")),
    Monster(N_("Green Dragon"), 8, None),
    Monster(N_("Platinum Dragon"), 21, None),
    Monster(N_("Red Dragon"), 10, N_("cocktail")),
    Monster(N_("Silver Dragon"), 10, None),
    Monster(N_("White Dragon"), 6, N_("tooth")),
    Monster(N_("Dragon Turtle"), 13, N_("shell")),
    Monster(N_("Dryad"), 2, N_("acorn")),
    Monster(N_("Dwarf"), 1, N_("drawers")),
    Monster(N_("Eel"), 2, N_("sashimi")),
    Monster(N_("Efreet"), 10, N_("cinder")),
    Monster(N_("Sand Elemental"), 8, N_("glass")),
    Monster(N_("Bacon Elemental"), 10, N_("bit")),
    Monster(N_("Porn Elemental"), 12, N_("lube")),
    Monster(N_("Cheese Elemental"), 14, N_("curd")),
    Monster(N_("Hair Elemental"), 16, N_("follicle")),
    Monster(N_("Swamp Elf"), 1, N_("lilypad")),
    Monster(N_("Brown Elf"), 1, N_("tusk")),
    Monster(N_("Sea Elf"), 1, N_("jerkin")),
    Monster(N_("Ettin"), 10, N_("fur")),
    Monster(N_("Frog"), 0, N_("leg")),
    Monster(N_("Violet Fungi"), 3, N_("spore")),
    Monster(N_("Gargoyle"), 4, N_("gravel")),
    Monster(N_("Gelatinous Cube"), 4, N_("jam")),
    Monster(N_("Ghast"), 4, N_("vomit")),
    Monster(N_("Ghost"), 10, None),
    Monster(N_("Ghoul"), 2, N_("muscle")),
    Monster(N_("Humidity Giant"), 12, N_("drops")),
    Monster(N_("Beef Giant"), 11, N_("steak")),
    Monster(N_("Quartz Giant"), 10, N_("crystal")),
    Monster(N_("Porcelain Giant"), 9, N_("fixture")),
    Monster(N_("Rice Giant"), 8, N_("grain")),
    Monster(N_("Cloud Giant"), 12, N_("condensation")),
    Monster(N_("Fire Giant"), 11, N_("cigarettes")),
    Monster(N_("Frost Giant"), 10, N_("snowman")),
    Monster(N_("Hill Giant"), 8, N_("corpse")),
    Monster(N_("Stone Giant"), 9, N_("hatchling")),
    Monster(N_("Storm Giant"), 15, N_("barometer")),
    Monster(N_("Mini Giant"), 4, N_("pompadour")),
    Monster(N_("Gnoll"), 2, N_("collar")),
    Monster(N_("Gnome"), 1, N_("hat")),
    Monster(N_("Goblin"), 1, N_("ear")),
    Monster(N_("Grid Bug"), 1, N_("carapace")),
    Monster(N_("Jellyrock"), 9, N_("seedling")),
    Monster(N_("Beer Golem"), 15, N_("foam")),
    Monster(N_("Oxygen Golem"), 17, N_("platelet")),
    Monster(N_("Cardboard Golem"), 14, N_("recycling")),
    Monster(N_("Rubber Golem"), 16, N_("ball")),
    Monster(N_("Leather Golem"), 15, N_("fob")),
    Monster(N_("Gorgon"), 8, N_("testicle")),
    Monster(N_("Gray Ooze"), 3, N_("gravy")),
    Monster(N_("Green Slime"), 2, N_("sample")),
    Monster(N_("Griffon"), 7, N_("nest")),
    Monster(N_("Banshee"), 7, N_("larynx")),
    Monster(N_("Harpy"), 3, N_("mascara")),
    Monster(N_("Hell Hound"), 5, N_("tongue")),
    Monster(N_("Hippocampus"), 4, N_("mane")),
    Monster(N_("Hippogriff"), 3, N_("egg")),
    Monster(N_("Hobgoblin"), 1, N_("patella")),
    Monster(N_("Homunculus"), 2, N_("fluid")),
    Monster(N_("Hydra"), 8, N_("gyrum")),
    Monster(N_("Imp"), 2, N_("tail")),
    Monster(N_("Invisible Stalker"), 8, None),
    Monster(N_("Iron Peasant"), 3, N_("chaff")),
    Monster(N_("Jumpskin"), 3, N_("shin")),
    Monster(N_("Kobold"), 1, N_("penis")),
    Monster(N_("Leprechaun"), 1, N_("wallet")),
    Monster(N_("Leucrotta"), 6, N_("hoof")),
    Monster(N_("Lich"), 11, N_("crown")),
    Monster(N_("Lizard Man"), 2, N_("tail")),
    Monster(N_("Lurker"), 10, N_("sac")),
    Monster(N_("Manticore"), 6, N_("spike")),
    Monster(N_("Mastodon"), 12, N_("tusk")),
    Monster(N_("Medusa"), 6, N_("eye")),
    Monster(N_("Multicell"), 2, N_("dendrite")),
    Monster(N_("Pirate"), 1, N_("booty")),
    Monster(N_("Berserker"), 1, N_("shirt")),
    Monster(N_("Caveman"), 2, N_("club")),
    Monster(N_("Dervish"), 1, N_("robe")),
    Monster(N_("Merman"), 1, N_("trident")),
    Monster(N_("Mermaid"), 1, N_("gills")),
    Monster(N_("Mimic"), 9, N_("hinge")),
    Monster(N_("Mind Flayer"), 8, N_("tentacle")),
    Monster(N_("Minotaur"), 6, N_("map")),
    Monster(N_("Yellow Mold"), 1, N_("spore")),
    Monster(N_("Morkoth"), 7, N_("teeth")),
    Monster(N_("Mummy"), 6, N_("gauze")),
    Monster(N_("Naga"), 9, N_("rattle")),
    Monster(N_("Nebbish"), 1, N_("belly")),
    Monster(N_("Neo-Otyugh"), 11, N_("organ ")),
    Monster(N_("Nixie"), 1, N_("webbing")),
    Monster(N_("Nymph"), 3, N_("hanky")),
    Monster(N_("Ochre Jelly"), 6, N_("nucleus")),
    Monster(N_("Octopus"), 2, N_("beak")),
    Monster(N_("Ogre"), 4, N_("talon")),
    Monster(N_("Ogre Mage"), 5, N_("apparel")),
    Monster(N_("Orc"), 1, N_("snout")),
    Monster(N_("Otyugh"), 7, N_("organ")),
    Monster(N_("Owlbear"), 5, N_("feather")),
    Monster(N_("Pegasus"), 4, N_("aileron")),
    Monster(N_("Peryton"), 4, N_("antler")),
    Monster(N_("Piercer"), 3, N_("tip")),
    Monster(N_("Pixie"), 1, N_("dust")),
    Monster(N_("Man-o-war"), 3, N_("tentacle")),
    Monster(N_("Purple Worm"), 15, N_("dung")),
    Monster(N_("Quasit"), 3, N_("tail")),
    Monster(N_("Rakshasa"), 7, N_("pajamas")),
    Monster(N_("Rat"), 0, N_("tail")),
    Monster(N_("Remorhaz"), 11, N_("protrusion")),
    Monster(N_("Roc"), 18, N_("wing")),
    Monster(N_("Roper"), 11, N_("twine")),
    Monster(N_("Rot Grub"), 1, N_("eggsac")),
    Monster(N_("Rust Monster"), 5, N_("shavings")),
    Monster(N_("Satyr"), 5, N_("hoof")),
    Monster(N_("Sea Hag"), 3, N_("wart")),
    Monster(N_("Silkie"), 3, N_("fur")),
    Monster(N_("Shadow"), 3, N_("silhouette")),
    Monster(N_("Shambling Mound"), 10, N_("mulch")),
    Monster(N_("Shedu"), 9, N_("hoof")),
    Monster(N_("Shrieker"), 3, N_("stalk")),
    Monster(N_("Skeleton"), 1, N_("clavicle")),
    Monster(N_("Spectre"), 7, N_("vestige")),
    Monster(N_("Sphinx"), 10, N_("paw")),
    Monster(N_("Spider"), 0, N_("web")),
    Monster(N_("Sprite"), 1, N_("can")),
    Monster(N_("Stirge"), 1, N_("proboscis")),
    Monster(N_("Stun Bear"), 5, N_("tooth")),
    Monster(N_("Stun Worm"), 2, N_("trode")),
    Monster(N_("Su-monster"), 5, N_("tail")),
    Monster(N_("Sylph"), 3, N_("thigh")),
    Monster(N_("Titan"), 20, N_("sandal")),
    Monster(N_("Trapper"), 12, N_("shag")),
    Monster(N_("Treant"), 10, N_("acorn")),
    Monster(N_("Triton"), 3, N_("scale")),
    Monster(N_("Troglodyte"), 2, N_("tail")),
    Monster(N_("Troll"), 6, N_("hide")),
    Monster(N_("Umber Hulk"), 8, N_("claw")),
    Monster(N_("Unicorn"), 4, N_("blood")),
    Monster(N_("Vampire"), 8, N_("pancreas")),
    Monster(N_("Wight"), 4, N_("lung")),
    Monster(N_("Will-o'-the-Wisp"), 9, N_("wisp")),
    Monster(N_("Wraith"), 5, N_("finger")),
    Monster(N_("Wyvern"), 7, N_("wing")),
    Monster(N_("Xorn"), 7, N_("jaw")),
    Monster(N_("Yeti"), 4, N_("fur")),
    Monster(N_("Zombie"), 2, N_("forehead")),
    Monster(N_("Wasp"), 0, N_("stinger")),
    Monster(N_("Rat"), 1, N_("tail")),
    Monster(N_("Bunny"), 0, N_("ear")),
    Monster(N_("Moth"), 0, N_("dust")),
    Monster(N_("Beagle"), 0, N_("collar")),
    Monster(N_("Midge"), 0, N_("corpse")),
    Monster(N_("Ostrich"), 1, N_("beak")),
    Monster(N_("Billy Goat"), 1, N_("beard")),
    Monster(N_("Bat"), 1, N_("wing")),
    Monster(N_("Koala"), 2, N_("heart")),
    Monster(N_("Wolf"), 2, N_("paw")),
    Monster(N_("Whippet"), 2, N_("collar")),
    Monster(N_("Uruk"), 2, N_("boot")),
    Monster(N_("Poroid"), 4, N_("node")),
    Monster(N_("Moakum"), 8, N_("frenum")),
    Monster(N_("Fly"), 0, None),
    Monster(N_("Hogbird"), 3, N_("curl")),
    Monster(N_("Wolog"), 4, N_("lemma")),
]


@dataclass
class Race:
    name: str
    attr: T.List[StatType]


RACES = [
    Race(N_("Half Orc"), [StatType.hp_max]),
    Race(N_("Half Man"), [StatType.charisma]),
    Race(N_("Half Halfling"), [StatType.dexterity]),
    Race(N_("Double Hobbit"), [StatType.strength]),
    Race(N_("Hob-Hobbit"), [StatType.dexterity, StatType.condition]),
    Race(N_("Low Elf"), [StatType.condition]),
    Race(N_("Dung Elf"), [StatType.wisdom]),
    Race(N_("Talking Pony"), [StatType.mp_max, StatType.intelligence]),
    Race(N_("Gyrognome"), [StatType.dexterity]),
    Race(N_("Lesser Dwarf"), [StatType.condition]),
    Race(N_("Crested Dwarf"), [StatType.charisma]),
    Race(N_("Eel Man"), [StatType.dexterity]),
    Race(N_("Panda Man"), [StatType.condition, StatType.strength]),
    Race(N_("Trans-Kobold"), [StatType.wisdom]),
    Race(N_("Enchanted Motorcycle"), [StatType.mp_max]),
    Race(N_("Will o' the Wisp"), [StatType.wisdom]),
    Race(N_("Battle-Finch"), [StatType.dexterity, StatType.intelligence]),
    Race(N_("Double Wookiee"), [StatType.strength]),
    Race(N_("Skraeling"), [StatType.wisdom]),
    Race(N_("Demicanadian"), [StatType.condition]),
    Race(N_("Land Squid"), [StatType.strength, StatType.hp_max]),
]


@dataclass
class Class:
    name: str
    attr: T.List[StatType]


CLASSES = [
    Class(N_("Ur-Paladin"), [StatType.wisdom, StatType.condition]),
    Class(N_("Voodoo Princess"), [StatType.intelligence, StatType.charisma]),
    Class(N_("Robot Monk"), [StatType.strength]),
    Class(N_("Mu-Fu Monk"), [StatType.dexterity]),
    Class(N_("Mage Illusioner"), [StatType.intelligence, StatType.mp_max]),
    Class(N_("Shiv-Knight"), [StatType.dexterity]),
    Class(N_("Inner Mason"), [StatType.condition]),
    Class(N_("Fighter/Organist"), [StatType.charisma, StatType.strength]),
    Class(N_("Puma Burgular"), [StatType.dexterity]),
    Class(N_("Runeloremaster"), [StatType.wisdom]),
    Class(N_("Hunter Strangler"), [StatType.dexterity, StatType.intelligence]),
    Class(N_("Battle-Felon"), [StatType.strength]),
    Class(N_("Tickle-Mimic"), [StatType.wisdom, StatType.intelligence]),
    Class(N_("Slow Poisoner"), [StatType.condition]),
    Class(N_("Bastard Lunatic"), [StatType.condition]),
    Class(N_("Lowling"), [StatType.wisdom]),
    Class(N_("Birdrider"), [StatType.wisdom]),
    Class(N_("Vermineer"), [StatType.intelligence]),
]

TITLES = [
    N_("Mr."),
    N_("Mrs."),
    N_("Sir"),
    N_("Sgt."),
    N_("Ms."),
    N_("Captain"),
    N_("Chief"),
    N_("Admiral"),
    N_("Saint"),
]

IMPRESSIVE_TITLES = [
    N_("King"),
    N_("Queen"),
    N_("Lord"),
    N_("Lady"),
    N_("Viceroy"),
    N_("Mayor"),
    N_("Prince"),
    N_("Princess"),
    N_("Chief"),
    N_("Boss"),
    N_("Archbishop"),
]
